### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by aarlin** [HueSamai/SpawnEnemies#1]
is it possible to add the C# project into this repository?

**Comment by HueSamai** [comment]
Will set a reminder for myself to do that. The code will not be up to date with all the new Cement stuff, but if you are interested in porting it over, on the wiki there will be more info on doing that.

**Comment by aarlin** [comment]
Sounds good, thank you

**Comment by HueSamai** [comment]
I migrated the mod to melon loader, @aarlin. Here's the source code: https://github.com/HueSamai/CementMods/blob/main/BetterSpawnEnemies/BetterSpawnEnemies.cs
